
# <p style="text-align: center;">Large Weather and Decrees</p>




to do : 

nan and nan, pas possible, eclaircir le full jin. peut etre nettoyer dabort tt les decision=1 faire les year manquant, puis rajouter tt les communes qui n'y sont pas


envisager de travailler sur le departement ou la region qui a le plus de secheresse


enrichir avec latitude longitude, prendre directement les missing en dataframe et les rajouter à la mano, laisser en commentaire le truc qui les enrichie

In [1]:
#!pip install cartopy
#!pip install imageio

## Import libraries

In [2]:
import pandas as pd
import numpy as np

import glob
import os

import requests

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

import zipfile

import xarray as xr

import folium
from folium.plugins import MarkerCluster

import pandas as pd
from geopy.geocoders import Nominatim

import geopandas as gpd
import cartopy.crs as ccrs

import imageio

from sklearn.neighbors import KDTree
from sklearn.neighbors import BallTree

from sklearn.preprocessing import RobustScaler

## Set parameters

In [3]:
decree_filename_base = 'arrete_'
decrees_folder_name = './../../data/raw/decrees'
communes_folder_name = './../../data/raw/opendatasoft'
weather_folder_name = './../../data/raw/weather/era5'
weather_ncfiles_folder_name = './../../data/raw/weather/era5/ncfiles2'
processed_data_folder_name = './../../data/processed'
output_data_folder_name = './../../data/processed/output'
decrees_filename = 'decrees.parquet'
decrees_locations_filename = 'decrees_locations.parquet'
communes_csv_filename = 'correspondance-code-insee-code-postal-202410.csv'
weather_filename = 'weather2.parquet'
weather_shema_filename = 'weather_shema2.csv'
weather_yearly_filename = 'weather2_yearly.parquet'
weather_yearly_shema_filename = 'weather_shema2_yearly.csv'
drought_filename = 'drought.parquet'
drought_shema_filename = 'drought_shema.csv'
drought_yearly_filename = 'drought_yearly.parquet'
drought_yearly_shema_filename = 'drought_yearly_shema.csv'
drought_commune_clean_filename = 'drought_commune_clean.parquet'
drought_commune_clean_shema_filename = 'drought_commune_clean_shema.csv'
drought_weather_filename = 'drought_weather.parquet'
drought_weather_shema_filename = 'drought_weather_shema.csv'
#weather_zip_file = "193fcd51a8958175843ecbbcaba057c8.zip"

## Load Weather data

| Column    | Description                                      |
|-----------|--------------------------------------------------|
| date      | The date of the observation.                     |
| latitude  | The latitude coordinate of the observation point.|
| longitude | The longitude coordinate of the observation point.|
| number    | A unique identifier for the observation.         |
| expver    | Experiment version number.                       |
| u10       | 10-meter U-component of wind (eastward wind).    |
| v10       | 10-meter V-component of wind (northward wind).   |
| t2m       | 2-meter temperature (air temperature at 2 meters above the surface).|
| sp        | Surface pressure.                                |
| tp        | Total precipitation.                             |
| e         | Evaporation.                                     |
| sro       | Surface runoff.                                  |
| tcrw      | Total column water vapor.                        |
| stl1      | Soil temperature level 1.                        |
| stl2      | Soil temperature level 2.                        |
| slt       | Soil type.                                       |
| swvl1     | Volumetric soil water layer 1.                   |
| swvl2     | Volumetric soil water layer 2.                   |
| cvh       | High vegetation cover.                           |
| cvl       | Low vegetation cover.                            |
| tvh       | High vegetation type.                            |
| tvl       | Low vegetation type.                             |

In [4]:
df_yearly_weather = pd.read_parquet(os.path.join(processed_data_folder_name, weather_yearly_filename))
weather_yearly_shema = pd.read_csv(os.path.join(processed_data_folder_name, weather_yearly_shema_filename), index_col=0).squeeze("columns")
df_yearly_weather = df_yearly_weather.astype(weather_yearly_shema.to_dict())

In [5]:
df_yearly_weather.head()

,latitude,longitude,year,t2m_z_sum,t2m_z_mean,tp_z_sum,tp_z_mean,e_z_sum,e_z_mean,pev_z_sum,...,stl1_sum,stl1_mean,stl2_sum,stl2_mean,slt_sum,slt_mean,swvl1_sum,swvl1_mean,swvl2_sum,swvl2_mean
0,42.5,-5.0,1940,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,...,131.224976,10.935414,131.221069,10.935089,36.0,3.0,3.491412,0.290951,3.582633,0.298553
1,42.5,-5.0,1941,0.000000,0.000000,-1.414214,-0.117851,1.414214,0.117851,-1.414214,...,130.369019,10.864085,129.770386,10.814198,36.0,3.0,3.291583,0.274299,3.486492,0.290541
2,42.5,-5.0,1942,2.590982,0.215915,0.948012,0.079001,-2.155737,-0.179645,-0.856798,...,132.005249,11.000438,131.522339,10.960195,36.0,3.0,3.473109,0.289426,3.584625,0.298719
3,42.5,-5.0,1943,3.948252,0.329021,-5.062950,-0.421913,-0.876471,-0.073039,-7.460276,...,143.968140,11.997345,143.213501,11.934459,36.0,3.0,3.147441,0.262287,3.267897,0.272325
4,42.5,-5.0,1944,-0.020748,-0.001729,-2.657244,-0.221437,5.106711,0.425559,-5.488278,...,133.577759,11.131480,133.382690,11.115224,36.0,3.0,2.850830,0.237569,2.922482,0.243540

In [6]:
df_yearly_weather.columns

Index(['latitude', 'longitude', 'year', 't2m_z_sum', 't2m_z_mean', 'tp_z_sum',
       'tp_z_mean', 'e_z_sum', 'e_z_mean', 'pev_z_sum', 'pev_z_mean',
       'stl1_z_sum', 'stl1_z_mean', 'stl2_z_sum', 'stl2_z_mean', 'slt_z_sum',
       'slt_z_mean', 'swvl1_z_sum', 'swvl1_z_mean', 'swvl2_z_sum',
       'swvl2_z_mean', 't2m_sum', 't2m_mean', 'tp_sum', 'tp_mean', 'e_sum',
       'e_mean', 'pev_sum', 'pev_mean', 'stl1_sum', 'stl1_mean', 'stl2_sum',
       'stl2_mean', 'slt_sum', 'slt_mean', 'swvl1_sum', 'swvl1_mean',
       'swvl2_sum', 'swvl2_mean'],
      dtype='object')

In [7]:
df_yearly_weather.dtypes

latitude        float64
longitude       float64
year              int32
t2m_z_sum       float64
t2m_z_mean      float64
tp_z_sum        float64
tp_z_mean       float64
e_z_sum         float64
e_z_mean        float64
pev_z_sum       float64
pev_z_mean      float64
stl1_z_sum      float64
stl1_z_mean     float64
stl2_z_sum      float64
stl2_z_mean     float64
slt_z_sum       float64
slt_z_mean      float64
swvl1_z_sum     float64
swvl1_z_mean    float64
swvl2_z_sum     float64
swvl2_z_mean    float64
t2m_sum         float32
t2m_mean        float32
tp_sum          float32
tp_mean         float32
e_sum           float32
e_mean          float32
pev_sum         float32
pev_mean        float32
stl1_sum        float32
stl1_mean       float32
stl2_sum        float32
stl2_mean       float32
slt_sum         float32
slt_mean        float32
swvl1_sum       float32
swvl1_mean      float32
swvl2_sum       float32
swvl2_mean      float32
dtype: object

In [8]:
print(df_yearly_weather.isna().sum())  # Count missing values

latitude           0
longitude          0
year               0
t2m_z_sum          0
t2m_z_mean      1925
tp_z_sum           0
tp_z_mean       1925
e_z_sum            0
e_z_mean        1925
pev_z_sum          0
pev_z_mean      1925
stl1_z_sum         0
stl1_z_mean     1925
stl2_z_sum         0
stl2_z_mean     1925
slt_z_sum          0
slt_z_mean      1925
swvl1_z_sum        0
swvl1_z_mean    1925
swvl2_z_sum        0
swvl2_z_mean    1925
t2m_sum            0
t2m_mean           0
tp_sum             0
tp_mean            0
e_sum              0
e_mean             0
pev_sum            0
pev_mean           0
stl1_sum           0
stl1_mean          0
stl2_sum           0
stl2_mean          0
slt_sum            0
slt_mean           0
swvl1_sum          0
swvl1_mean         0
swvl2_sum          0
swvl2_mean         0
dtype: int64

In [9]:
# Filter the DataFrame to exclude the year 1940
df_yearly_weather[df_yearly_weather['year'] != 1940].isna().sum().sum()

0

In [10]:
df_yearly_weather.drop(df_yearly_weather[df_yearly_weather['year'] == 1940].index, inplace=True)

In [11]:
df_yearly_weather.isna().sum().sum()

0

### Note

>There are no missing values in weather data because they come from monthly ERA5 simulations based on real data. only missing in 1940 du to rolling window for featured parameters.

## Import Decrees

In [12]:


df_drought_yearly = pd.read_parquet(os.path.join(processed_data_folder_name, drought_yearly_filename))
drought_schema_yearly = pd.read_csv(os.path.join(processed_data_folder_name, drought_yearly_shema_filename), index_col=0).squeeze("columns")
df_drought_yearly = df_drought_yearly.astype(drought_schema_yearly.to_dict())

In [13]:
df_drought_yearly.head()

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration
43673,12018,BALAGUIER D OLT,1990-01-01,1990-09-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,272,1990,1,1
43674,12018,BALAGUIER D OLT,1992-03-01,1992-06-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,121,1992,1,1
43677,17118,CORIGNAC,1989-05-01,1989-12-31,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,244,1989,1,1
43678,17203,LANDRAIS,1990-01-01,1990-09-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,272,1990,1,1
43679,17260,NEUVICQ,1989-05-01,1989-12-31,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,244,1989,1,1

| Column    | Description                                      |
|-----------|--------------------------------------------------|
| date      | The date of the observation.                     |
| latitude  | The latitude coordinate of the observation point.|
| longitude | The longitude coordinate of the observation point.|
| number    | A unique identifier for the observation.         |
| expver    | Experiment version number.                       |
| u10       | 10-meter U-component of wind (eastward wind).    |
| v10       | 10-meter V-component of wind (northward wind).   |
| t2m       | 2-meter temperature (air temperature at 2 meters above the surface).|
| sp        | Surface pressure.                                |
| tp        | Total precipitation.                             |
| e         | Evaporation.                                     |
| sro       | Surface runoff.                                  |
| tcrw      | Total column water vapor.                        |
| stl1      | Soil temperature level 1.                        |
| stl2      | Soil temperature level 2.                        |
| slt       | Soil type.                                       |
| swvl1     | Volumetric soil water layer 1.                   |
| swvl2     | Volumetric soil water layer 2.                   |
| cvh       | High vegetation cover.                           |
| cvl       | Low vegetation cover.                            |
| tvh       | High vegetation type.                            |
| tvl       | Low vegetation type.                             |

## Import Locations

In [14]:
df_communes_location = pd.read_csv(os.path.join(communes_folder_name, communes_csv_filename), sep=";")

In [15]:
df_communes_location.head()

,Code INSEE,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,ID Geofla,Code Commune,Code Canton,Code Arrondissement,Code Département,Code Région
0,64012,64130,AINHARP,['PYRENEES-ATLANTIQUES'],['AQUITAINE'],['Commune simple'],232.0,1431.0,0.1,"43.25473886787848, -0.935719451957656","{""coordinates"": [[[-0.923667598351223, 43.2284...",3178,12,20,2,64,72
1,2A108,20126,EVISA,['CORSE-DU-SUD'],['CORSE'],['Commune simple'],1160.0,6720.0,0.2,"42.28525022904632, 8.820396904179216","{""coordinates"": [[[8.813203180956721, 42.23916...",1332,108,35,1,2A,94
2,28232,28240,MANOU,['EURE-ET-LOIR'],['CENTRE'],['Commune simple'],237.0,1361.0,0.6,"48.53638563478625, 0.962933887077251","{""coordinates"": [[[0.9962700204594641, 48.5274...",4524,232,17,4,28,24
3,62761,62128,SAINT-MARTIN-SUR-COJEUL,['PAS-DE-CALAIS'],['NORD-PAS-DE-CALAIS'],['Commune simple'],86.0,343.0,0.2,"50.22864782200462, 2.851919793535168","{""coordinates"": [[[2.862290324179924, 50.21323...",18319,761,20,1,62,31
4,56219,56460,SAINT-GUYOMARD,['MORBIHAN'],['BRETAGNE'],['Commune simple'],79.0,1979.0,1.0,"47.77934192534663, -2.502103749642248","{""coordinates"": [[[-2.481587975007875, 47.7614...",4824,219,19,3,56,53

In [16]:
df_communes_location['Code INSEE'].describe()

count     36742
unique    36742
top       64012
freq          1
Name: Code INSEE, dtype: object

## Decrees  Locations

In [17]:
def check_insee_coverage(df1, df2, insee_col1, insee_col2):
    # Step 1: Create copies of the dataframes to avoid modifying the input dataframes
    df1_copy = df1.copy()
    df2_copy = df2.copy()

    # Step 2: Remove spaces before and after in the INSEE code columns and remove leading zeros to ensure proper comparison
    df1_copy[insee_col1] = df1_copy[insee_col1].str.strip().str.lstrip('0')
    df2_copy[insee_col2] = df2_copy[insee_col2].str.strip().str.lstrip('0')

    # Step 3: Get the list of INSEE codes from df2
    insee_codes_df2 = df2_copy[insee_col2].unique()

    # Step 4: Check if all INSEE codes in df1 are present in df2
    all_in_df2 = df1_copy[insee_col1].isin(insee_codes_df2)

    # Step 5: Return the communes in df1 that are not in df2
    missing_communes = df1_copy[~all_in_df2]
    return missing_communes

# Example usage of the function
missing_communes = check_insee_coverage(df_drought_yearly, df_communes_location, 'insee', 'Code INSEE')
print(missing_communes[['insee', 'nom_commune']])

        insee        nom_commune
69059   79065        CHAMBROUTET
69059   79065        CHAMBROUTET
69706   59248       FORT MARDYCK
69706   59248       FORT MARDYCK
75499   13055          MARSEILLE
75499   13055          MARSEILLE
75499   13055          MARSEILLE
75783   62575          MOLINGHEM
94181   59248       FORT MARDYCK
94181   59248       FORT MARDYCK
97902   59540  SAINT POL SUR MER
97902   59540  SAINT POL SUR MER
97902   59540  SAINT POL SUR MER
165856  13055          MARSEILLE
165856  13055          MARSEILLE
165857  13055          MARSEILLE
169786  59248       FORT MARDYCK
175422  13055          MARSEILLE
193312  13055          MARSEILLE
193313  13055          MARSEILLE
193314  13055          MARSEILLE
194390  13055          MARSEILLE
194391  13055          MARSEILLE
205082  13055          MARSEILLE
237044  13055          MARSEILLE
241976  13055          MARSEILLE
260470  13055          MARSEILLE
276234  13055          MARSEILLE
290237  13055          MARSEILLE

In [18]:
unique_values = missing_communes[['insee', 'nom_commune']].drop_duplicates()
print(unique_values)

       insee        nom_commune
69059  79065        CHAMBROUTET
69706  59248       FORT MARDYCK
75499  13055          MARSEILLE
75783  62575          MOLINGHEM
97902  59540  SAINT POL SUR MER

In [19]:
missing_communes

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration
69059,79065,CHAMBROUTET,1989-05-01,1990-12-31,1991-12-04,1991-12-27,Sécheresse,SEC,Simple,INTX9110334A,Reconnue,609,1989,1,2
69059,79065,CHAMBROUTET,1989-05-01,1990-12-31,1991-12-04,1991-12-27,Sécheresse,SEC,Simple,INTX9110334A,Reconnue,609,1990,2,2
69706,59248,FORT MARDYCK,1990-01-01,1991-12-31,1992-07-31,1992-08-18,Sécheresse,SEC,Simple,INTX9210277A,Reconnue,729,1990,1,2
69706,59248,FORT MARDYCK,1990-01-01,1991-12-31,1992-07-31,1992-08-18,Sécheresse,SEC,Simple,INTX9210277A,Reconnue,729,1991,2,2
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1990,2,3
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1991,3,3
75783,62575,MOLINGHEM,1991-01-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,364,1991,1,1
94181,59248,FORT MARDYCK,1992-01-01,1993-12-31,1996-02-02,1996-02-14,Sécheresse,SEC,Simple,INTE9600039A,Reconnue,730,1992,1,2
94181,59248,FORT MARDYCK,1992-01-01,1993-12-31,1996-02-02,1996-02-14,Sécheresse,SEC,Simple,INTE9600039A,Reconnue,730,1993,2,2
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1995,1,3
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1996,2,3
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1997,3,3
165856,13055,MARSEILLE,1992-01-01,1993-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,546,1992,1,2
165856,13055,MARSEILLE,1992-01-01,1993-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,546,1993,2,2
165857,13055,MARSEILLE,1998-01-01,1998-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,180,1998,1,1
169786,59248,FORT MARDYCK,1996-01-01,1996-12-31,2001-12-27,2002-01-18,Sécheresse,SEC,Simple,INTE0100760A,Reconnue,365,1996,1,1
175422,13055,MARSEILLE,2002-01-01,2002-06-30,2004-08-25,2004-08-26,Sécheresse,SEC,Doublée,INTE0400656A,Reconnue,180,2002,1,1
193312,13055,MARSEILLE,2004-01-01,2004-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,90,2004,1,1
193313,13055,MARSEILLE,2005-01-01,2005-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,89,2005,1,1
193314,13055,MARSEILLE,2006-01-01,2006-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,89,2006,1,1
194390,13055,MARSEILLE,2007-01-01,2007-03-31,2008-08-07,2008-08-13,Sécheresse,SEC,Simple,IOCE0819658A,Reconnue,89,2007,1,1
194391,13055,MARSEILLE,2007-07-01,2007-09-30,2008-08-07,2008-08-13,Sécheresse,SEC,Simple,IOCE0819658A,Reconnue,91,2007,1,1
205082,13055,MARSEILLE,2008-01-01,2008-03-31,2009-10-16,2009-10-21,Sécheresse,SEC,Quadruplée,IOCE0924280A,Reconnue,90,2008,1,1
237044,13055,MARSEILLE,2016-07-01,2016-09-30,2017-07-25,2017-09-01,Sécheresse,SEC,Simple,INTE1719708A,Reconnue,91,2016,1,1
241976,13055,MARSEILLE,2017-07-01,2017-09-30,2018-07-10,2018-07-27,Sécheresse,SEC,Simple,INTE1818803A,Reconnue,91,2017,1,1
260470,13055,MARSEILLE,2019-07-01,2019-09-30,2020-07-28,2020-09-03,Sécheresse,SEC,Simple,INTE2019261A,Reconnue,91,2019,1,1
276234,13055,MARSEILLE,2022-04-01,2022-09-30,2023-04-03,2023-05-03,Sécheresse,SEC,Simple,IOME2308745A,Reconnue,182,2022,1,1
290237,13055,MARSEILLE,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1

In [20]:
df_drought_yearly['insee'].dtypes

dtype('O')

In [21]:
df_communes_location['Code INSEE'].dtypes

dtype('O')

In [22]:
df_communes_location[df_communes_location['Code INSEE'].str.strip()=='1339']

Empty DataFrame
Columns: [Code INSEE, Code Postal, Commune, Département, Région, Statut, Altitude Moyenne, Superficie, Population, geo_point_2d, geo_shape, ID Geofla, Code Commune, Code Canton, Code Arrondissement, Code Département, Code Région]
Index: []

In [23]:
print(df_communes_location.iloc[18260:18270])

      Code INSEE Code Postal                    Commune  \
18260      76612       76340       SAINT-MARTIN-AU-BOSC
18261      76186       76390                 CONTEVILLE
18262      97353       97370                MARIPASOULA
18263      01339       01600              SAINT-BERNARD
18264      74190       74440                   MORILLON
18265      67142       67480                 FORT-LOUIS
18266      21556       21270          SAINT-LEGER-TRIEY
18267      62139       62575                BLENDECQUES
18268      64189       64500                    CIBOURE
18269      47256       47210  SAINT-MARTIN-DE-VILLEREAL

                    Département                  Région                Statut  \
18260        ['SEINE-MARITIME']     ['HAUTE-NORMANDIE']    ['Commune simple']
18261        ['SEINE-MARITIME']     ['HAUTE-NORMANDIE']    ['Commune simple']
18262                ['GUYANE']              ['GUYANE']  ['Chef-lieu canton']
18263                   ['AIN']         ['RHONE-ALPES']    ['Commune simple']
18264          ['HAUTE-SAVOIE']         ['RHONE-ALPES']    ['Commune simple']
18265              ['BAS-RHIN']              ['ALSACE']    ['Commune simple']
18266             ["COTE-D'OR"]           ['BOURGOGNE']    ['Commune simple']
18267         ['PAS-DE-CALAIS']  ['NORD-PAS-DE-CALAIS']    ['Commune simple']
18268  ['PYRENEES-ATLANTIQUES']           ['AQUITAINE']    ['Commune simple']
18269        ['LOT-ET-GARONNE']           ['AQUITAINE']    ['Commune simple']

       Altitude Moyenne  Superficie  Population  \
18260             177.0       722.0         0.2
18261             240.0      1381.0         0.5
18262             189.0   1871833.0         7.6
18263             181.0       315.0         1.4
18264            1161.0      1439.0         0.6
18265             118.0      1225.0         0.3
18266             193.0      1049.0         0.2
18267              38.0       965.0         5.2
18268              29.0       745.0         6.8
18269             137.0       824.0         0.1

                                 geo_point_2d  \
18260    49.83163166279273, 1.668666541913017
18261     49.69666623236425, 1.63795618700569
18262   2.970884175940231, -53.75841931116502
18263   45.949383058071156, 4.742766284708344
18264  46.063239077228694, 6.6731823774131005
18265    48.79873101842311, 8.052613849175353
18266    47.31662016028507, 5.355256728385417
18267   50.715994434568735, 2.275363014480388
18268    43.3749892489221, -1.661337536260911
18269    44.64063064474696, 0.813494311456125

                                               geo_shape  ID Geofla  \
18260  {"coordinates": [[[1.6689260712931522, 49.8208...      26410
18261  {"coordinates": [[[1.65811765970296, 49.674555...      18590
18262  {"coordinates": [[[-53.317197766565286, 2.3401...         16
18263  {"coordinates": [[[4.744454528837308, 45.93742...      22843
18264  {"coordinates": [[[6.694278457414766, 46.03173...      21118
18265  {"coordinates": [[[8.017477073617899, 48.76275...      23069
18266  {"coordinates": [[[5.3446907279724805, 47.2952...       9216
18267  {"coordinates": [[[2.312580322089178, 50.70172...      14431
18268  {"coordinates": [[[-1.655186229478102, 43.3556...      34750
18269  {"coordinates": [[[0.8054335873590011, 44.6242...      33937

       Code Commune  Code Canton  Code Arrondissement Code Département  \
18260           612            5                    1               76
18261           186            2                    1               76
18262           353           16                    2               97
18263           339           34                    2               01
18264           190           23                    2               74
18265           142            3                    2               67
18266           556           25                    2               21
18267           139           62                    5               62
18268           189           45                    1               64
18269           256           35                    3               47

       Code Région
18260           23
18261           23
18262            3
18263           82
18264           82
18265           42
18266           26
18267           31
18268           72
18269           72

In [24]:
import pandas as pd

data = {
    'insee': [79065, 59248, 13055, 62575, 59540],
    'nom_commune': ['Chambrouet', 'Fort-Mardyck', 'Marseille', 'Molinghem', 'Saint-Pol-sur-Mer'],
    'latitude': [48.85341, 50.5432, 43.2965, 50.6542, 50.9912],
    'longitude': [2.3488, 2.9889, 5.3698, 2.2298, 2.3432],
    'department': ['Charente-Maritime', 'Nord', 'Bouches-du-Rhône', 'Pas-de-Calais', 'Nord'],
    'region': ['Nouvelle-Aquitaine', 'Hauts-de-France', 'Provence-Alpes-Côte d\'Azur', 'Hauts-de-France', 'Hauts-de-France']
}

df = pd.DataFrame(data)
print(df)

   insee        nom_commune  latitude  longitude         department  \
0  79065         Chambrouet  48.85341     2.3488  Charente-Maritime
1  59248       Fort-Mardyck  50.54320     2.9889               Nord
2  13055          Marseille  43.29650     5.3698   Bouches-du-Rhône
3  62575          Molinghem  50.65420     2.2298      Pas-de-Calais
4  59540  Saint-Pol-sur-Mer  50.99120     2.3432               Nord

                       region
0          Nouvelle-Aquitaine
1             Hauts-de-France
2  Provence-Alpes-Côte d'Azur
3             Hauts-de-France
4             Hauts-de-France

In [25]:
import folium

# Initialize the map centered around France
m = folium.Map(location=[46.603354, 1.888334], zoom_start=6)

# Data for communes
data = {
    'insee': [79065, 59248, 13055, 62575, 59540],
    'nom_commune': ['Chambrouet', 'Fort-Mardyck', 'Marseille', 'Molinghem', 'Saint-Pol-sur-Mer'],
    'latitude': [48.85341, 50.5432, 43.2965, 50.6542, 50.9912],
    'longitude': [2.3488, 2.9889, 5.3698, 2.2298, 2.3432],
    'department': ['Charente-Maritime', 'Nord', 'Bouches-du-Rhône', 'Pas-de-Calais', 'Nord'],
    'region': ['Nouvelle-Aquitaine', 'Hauts-de-France', 'Provence-Alpes-Côte d\'Azur', 'Hauts-de-France', 'Hauts-de-France'],
    'department_number': ['17', '59', '13', '62', '59']
}

# Add markers for each commune with department and region info
for i in range(len(data['nom_commune'])):
    folium.Marker(
        location=[data['latitude'][i], data['longitude'][i]],
        popup=f"{data['nom_commune'][i]}, Dept: {data['department'][i]} ({data['department_number'][i]}), Region: {data['region'][i]}"
    ).add_to(m)

# Save the map to an HTML file
m.save('communes_map.html')

In [26]:
m

In [27]:
'''

from geopy.geocoders import Nominatim
import pandas as pd
import folium

# Create a DataFrame with the INSEE codes and commune names
data = {
    'insee': ['79065', '59248', '13055', '62575', '59540'],
    'nom_commune': ['CHAMBROUTET', 'FORT MARDYCK', 'MARSEILLE', 'MOLINGHEM', 'SAINT POL SUR MER']
}
df_communes = pd.DataFrame(data)

# Initialize Nominatim API
geolocator = Nominatim(user_agent="insee_locator")

# Function to get latitude and longitude
def get_lat_long(commune_name):
    try:
        location = geolocator.geocode(f"{commune_name}, France")
        if location:
            return location.latitude, location.longitude
        else:
            return None, None
    except Exception as e:
        return None, None

# Function to get department and region information
def get_department_region(commune_name):
    try:
        location = geolocator.geocode(f"{commune_name}, France")
        if location:
            location_detail = geolocator.reverse((location.latitude, location.longitude), language='fr')
            if location_detail and 'address' in location_detail.raw:
                address = location_detail.raw['address']
                departement = address.get('county', None)
                departement_number = address.get('state_code', None)
                region = address.get('state', None)
                return departement, departement_number, region
        return None, None, None
    except Exception as e:
        return None, None, None

# Apply the function to get latitude, longitude, department, and region
df_communes[['latitude', 'longitude']] = df_communes['nom_commune'].apply(
    lambda x: pd.Series(get_lat_long(x))
)

df_communes[['departement', 'departement_number', 'region']] = df_communes['nom_commune'].apply(
    lambda x: pd.Series(get_department_region(x))
)

# Create a Folium map centered at an approximate central location in France
map_center = [46.603354, 1.888334]
communes_map = folium.Map(location=map_center, zoom_start=6)

# Add markers for each commune with a popup containing its information
for _, row in df_communes.iterrows():
    if pd.notna(row['latitude']) and pd.notna(row['longitude']):
        popup_text = (
            f"Commune: {row['nom_commune']}<br>"
            f"INSEE Code: {row['insee']}<br>"
            f"Department: {row['departement']} ({row['departement_number']})<br>"
            f"Region: {row['region']}"
        )
        folium.Marker(
            location=[row['latitude'], row['longitude']],
            popup=folium.Popup(popup_text, max_width=300)
        ).add_to(communes_map)

# Save the map to an HTML file
communes_map.save('communes_map.html')

# Print the DataFrame with all the information
print(df_communes)

# Example output (Note: The actual coordinates and department information depend on the geocoder's response)
#     insee          nom_commune   latitude   longitude      departement   departement_number   region
# 0  79065         CHAMBROUTET  46.7890     -0.5678      Deux-Sèvres       79                Nouvelle-Aquitaine
# 1  59248        FORT MARDYCK  51.0356      2.3314      Nord             59                Hauts-de-France
# 2  13055           MARSEILLE  43.2965      5.3698      Bouches-du-Rhône 13                Provence-Alpes-Côte d'Azur
# 3  62575           MOLINGHEM  50.6631      2.3387      Pas-de-Calais    62                Hauts-de-France
# 4  59540   SAINT POL SUR MER  51.0250      2.3333      Nord             59                Hauts-de-France


'''

'\n\nfrom geopy.geocoders import Nominatim\nimport pandas as pd\nimport folium\n\n# Create a DataFrame with the INSEE codes and commune names\ndata = {\n    \'insee\': [\'79065\', \'59248\', \'13055\', \'62575\', \'59540\'],\n    \'nom_commune\': [\'CHAMBROUTET\', \'FORT MARDYCK\', \'MARSEILLE\', \'MOLINGHEM\', \'SAINT POL SUR MER\']\n}\ndf_communes = pd.DataFrame(data)\n\n# Initialize Nominatim API\ngeolocator = Nominatim(user_agent="insee_locator")\n\n# Function to get latitude and longitude\ndef get_lat_long(commune_name):\n    try:\n        location = geolocator.geocode(f"{commune_name}, France")\n        if location:\n            return location.latitude, location.longitude\n        else:\n            return None, None\n    except Exception as e:\n        return None, None\n\n# Function to get department and region information\ndef get_department_region(commune_name):\n    try:\n        location = geolocator.geocode(f"{commune_name}, France")\n        if location:\n            location_detail = geolocator.reverse((location.latitude, location.longitude), language=\'fr\')\n            if location_detail and \'address\' in location_detail.raw:\n                address = location_detail.raw[\'address\']\n                departement = address.get(\'county\', None)\n                departement_number = address.get(\'state_code\', None)\n                region = address.get(\'state\', None)\n                return departement, departement_number, region\n        return None, None, None\n    except Exception as e:\n        return None, None, None\n\n# Apply the function to get latitude, longitude, department, and region\ndf_communes[[\'latitude\', \'longitude\']] = df_communes[\'nom_commune\'].apply(\n    lambda x: pd.Series(get_lat_long(x))\n)\n\ndf_communes[[\'departement\', \'departement_number\', \'region\']] = df_communes[\'nom_commune\'].apply(\n    lambda x: pd.Series(get_department_region(x))\n)\n\n# Create a Folium map centered at an approximate central location in France\nmap_center = [46.603354, 1.888334]\ncommunes_map = folium.Map(location=map_center, zoom_start=6)\n\n# Add markers for each commune with a popup containing its information\nfor _, row in df_communes.iterrows():\n    if pd.notna(row[\'latitude\']) and pd.notna(row[\'longitude\']):\n        popup_text = (\n            f"Commune: {row[\'nom_commune\']}<br>"\n            f"INSEE Code: {row[\'insee\']}<br>"\n            f"Department: {row[\'departement\']} ({row[\'departement_number\']})<br>"\n            f"Region: {row[\'region\']}"\n        )\n        folium.Marker(\n            location=[row[\'latitude\'], row[\'longitude\']],\n            popup=folium.Popup(popup_text, max_width=300)\n        ).add_to(communes_map)\n\n# Save the map to an HTML file\ncommunes_map.save(\'communes_map.html\')\n\n# Print the DataFrame with all the information\nprint(df_communes)\n\n# Example output (Note: The actual coordinates and department information depend on the geocoder\'s response)\n#     insee          nom_commune   latitude   longitude      departement   departement_number   region\n# 0  79065         CHAMBROUTET  46.7890     -0.5678      Deux-Sèvres       79                Nouvelle-Aquitaine\n# 1  59248        FORT MARDYCK  51.0356      2.3314      Nord             59                Hauts-de-France\n# 2  13055           MARSEILLE  43.2965      5.3698      Bouches-du-Rhône 13                Provence-Alpes-Côte d\'Azur\n# 3  62575           MOLINGHEM  50.6631      2.3387      Pas-de-Calais    62                Hauts-de-France\n# 4  59540   SAINT POL SUR MER  51.0250      2.3333      Nord             59                Hauts-de-France\n\n\n'

In [28]:
#communes_map

In [29]:
import pandas as pd

data = {
    'insee': [79065, 59248, 13055, 62575, 59540],
    'nom_commune': ['CHAMBROUTET', 'FORT MARDYCK', 'MARSEILLE', 'MOLINGHEM', 'SAINT POL SUR MER'],
    'latitude': [46.7890, 51.0356, 43.2965, 50.6631, 51.0250],
    'longitude': [-0.5678, 2.3314, 5.3698, 2.3387, 2.3333],
    'departement': ['Deux-Sèvres', 'Nord', 'Bouches-du-Rhône', 'Pas-de-Calais', 'Nord'],
    'departement_number': [79, 59, 13, 62, 59],
    'region': ['Nouvelle-Aquitaine', 'Hauts-de-France', 'Provence-Alpes-Côte d\'Azur', 'Hauts-de-France', 'Hauts-de-France']
}

df = pd.DataFrame(data)
print(df)

   insee        nom_commune  latitude  longitude       departement  \
0  79065        CHAMBROUTET   46.7890    -0.5678       Deux-Sèvres
1  59248       FORT MARDYCK   51.0356     2.3314              Nord
2  13055          MARSEILLE   43.2965     5.3698  Bouches-du-Rhône
3  62575          MOLINGHEM   50.6631     2.3387     Pas-de-Calais
4  59540  SAINT POL SUR MER   51.0250     2.3333              Nord

   departement_number                      region
0                  79          Nouvelle-Aquitaine
1                  59             Hauts-de-France
2                  13  Provence-Alpes-Côte d'Azur
3                  62             Hauts-de-France
4                  59             Hauts-de-France

In [30]:
import pandas as pd
import numpy as np

data = {
    'insee': ['79065', '59248', '13055', '62575', '59540'],
    'nom_commune': ['CHAMBROUTET', 'FORT MARDYCK', 'MARSEILLE', 'MOLINGHEM', 'SAINT POL SUR MER'],
    'new_insee': ['79049', '59183', np.nan, '62473', '59183'],
    'new_commune': ['BRESSUIRE', 'DUNKERQUE', np.nan, 'ISBERGUES', 'DUNKERQUE'],
}

df = pd.DataFrame(data)

# New rows for MARSEILLE
marseille_data = [
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13207', 'new_commune': 'MARSEILLE--7E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13203', 'new_commune': 'MARSEILLE--3E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13211', 'new_commune': 'MARSEILLE-11E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13204', 'new_commune': 'MARSEILLE--4E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13215', 'new_commune': 'MARSEILLE-15E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13201', 'new_commune': 'MARSEILLE--1ER-ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13210', 'new_commune': 'MARSEILLE-10E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13208', 'new_commune': 'MARSEILLE--8E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13205', 'new_commune': 'MARSEILLE--5E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13212', 'new_commune': 'MARSEILLE-12E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13214', 'new_commune': 'MARSEILLE-14E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13202', 'new_commune': 'MARSEILLE--2E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13209', 'new_commune': 'MARSEILLE--9E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13213', 'new_commune': 'MARSEILLE-13E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13206', 'new_commune': 'MARSEILLE--6E--ARRONDISSEMENT'},
    {'insee': '13055', 'nom_commune': 'MARSEILLE', 'new_insee': '13216', 'new_commune': 'MARSEILLE-16E--ARRONDISSEMENT'},
]

# Convert new data to DataFrame
marseille_df = pd.DataFrame(marseille_data)

# Remove the initial MARSEILLE row
df = df[df['nom_commune'] != 'MARSEILLE']

# Concatenate the original DataFrame with the new rows
df_new_insee = pd.concat([df, marseille_df], ignore_index=True)

print(df_new_insee)

    insee        nom_commune new_insee                    new_commune
0   79065        CHAMBROUTET     79049                      BRESSUIRE
1   59248       FORT MARDYCK     59183                      DUNKERQUE
2   62575          MOLINGHEM     62473                      ISBERGUES
3   59540  SAINT POL SUR MER     59183                      DUNKERQUE
4   13055          MARSEILLE     13207  MARSEILLE--7E--ARRONDISSEMENT
5   13055          MARSEILLE     13203  MARSEILLE--3E--ARRONDISSEMENT
6   13055          MARSEILLE     13211  MARSEILLE-11E--ARRONDISSEMENT
7   13055          MARSEILLE     13204  MARSEILLE--4E--ARRONDISSEMENT
8   13055          MARSEILLE     13215  MARSEILLE-15E--ARRONDISSEMENT
9   13055          MARSEILLE     13201  MARSEILLE--1ER-ARRONDISSEMENT
10  13055          MARSEILLE     13210  MARSEILLE-10E--ARRONDISSEMENT
11  13055          MARSEILLE     13208  MARSEILLE--8E--ARRONDISSEMENT
12  13055          MARSEILLE     13205  MARSEILLE--5E--ARRONDISSEMENT
13  13055          MARSEILLE     13212  MARSEILLE-12E--ARRONDISSEMENT
14  13055          MARSEILLE     13214  MARSEILLE-14E--ARRONDISSEMENT
15  13055          MARSEILLE     13202  MARSEILLE--2E--ARRONDISSEMENT
16  13055          MARSEILLE     13209  MARSEILLE--9E--ARRONDISSEMENT
17  13055          MARSEILLE     13213  MARSEILLE-13E--ARRONDISSEMENT
18  13055          MARSEILLE     13206  MARSEILLE--6E--ARRONDISSEMENT
19  13055          MARSEILLE     13216  MARSEILLE-16E--ARRONDISSEMENT

In [31]:
missing_communes

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration
69059,79065,CHAMBROUTET,1989-05-01,1990-12-31,1991-12-04,1991-12-27,Sécheresse,SEC,Simple,INTX9110334A,Reconnue,609,1989,1,2
69059,79065,CHAMBROUTET,1989-05-01,1990-12-31,1991-12-04,1991-12-27,Sécheresse,SEC,Simple,INTX9110334A,Reconnue,609,1990,2,2
69706,59248,FORT MARDYCK,1990-01-01,1991-12-31,1992-07-31,1992-08-18,Sécheresse,SEC,Simple,INTX9210277A,Reconnue,729,1990,1,2
69706,59248,FORT MARDYCK,1990-01-01,1991-12-31,1992-07-31,1992-08-18,Sécheresse,SEC,Simple,INTX9210277A,Reconnue,729,1991,2,2
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1990,2,3
75499,13055,MARSEILLE,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1991,3,3
75783,62575,MOLINGHEM,1991-01-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,364,1991,1,1
94181,59248,FORT MARDYCK,1992-01-01,1993-12-31,1996-02-02,1996-02-14,Sécheresse,SEC,Simple,INTE9600039A,Reconnue,730,1992,1,2
94181,59248,FORT MARDYCK,1992-01-01,1993-12-31,1996-02-02,1996-02-14,Sécheresse,SEC,Simple,INTE9600039A,Reconnue,730,1993,2,2
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1995,1,3
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1996,2,3
97902,59540,SAINT POL SUR MER,1995-01-01,1997-06-30,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,911,1997,3,3
165856,13055,MARSEILLE,1992-01-01,1993-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,546,1992,1,2
165856,13055,MARSEILLE,1992-01-01,1993-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,546,1993,2,2
165857,13055,MARSEILLE,1998-01-01,1998-06-30,2000-12-27,2000-12-29,Sécheresse,SEC,Simple,INTE0000771A,Reconnue,180,1998,1,1
169786,59248,FORT MARDYCK,1996-01-01,1996-12-31,2001-12-27,2002-01-18,Sécheresse,SEC,Simple,INTE0100760A,Reconnue,365,1996,1,1
175422,13055,MARSEILLE,2002-01-01,2002-06-30,2004-08-25,2004-08-26,Sécheresse,SEC,Doublée,INTE0400656A,Reconnue,180,2002,1,1
193312,13055,MARSEILLE,2004-01-01,2004-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,90,2004,1,1
193313,13055,MARSEILLE,2005-01-01,2005-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,89,2005,1,1
193314,13055,MARSEILLE,2006-01-01,2006-03-31,2008-06-11,2008-06-14,Sécheresse,SEC,Simple,IOCE0814202A,Reconnue,89,2006,1,1
194390,13055,MARSEILLE,2007-01-01,2007-03-31,2008-08-07,2008-08-13,Sécheresse,SEC,Simple,IOCE0819658A,Reconnue,89,2007,1,1
194391,13055,MARSEILLE,2007-07-01,2007-09-30,2008-08-07,2008-08-13,Sécheresse,SEC,Simple,IOCE0819658A,Reconnue,91,2007,1,1
205082,13055,MARSEILLE,2008-01-01,2008-03-31,2009-10-16,2009-10-21,Sécheresse,SEC,Quadruplée,IOCE0924280A,Reconnue,90,2008,1,1
237044,13055,MARSEILLE,2016-07-01,2016-09-30,2017-07-25,2017-09-01,Sécheresse,SEC,Simple,INTE1719708A,Reconnue,91,2016,1,1
241976,13055,MARSEILLE,2017-07-01,2017-09-30,2018-07-10,2018-07-27,Sécheresse,SEC,Simple,INTE1818803A,Reconnue,91,2017,1,1
260470,13055,MARSEILLE,2019-07-01,2019-09-30,2020-07-28,2020-09-03,Sécheresse,SEC,Simple,INTE2019261A,Reconnue,91,2019,1,1
276234,13055,MARSEILLE,2022-04-01,2022-09-30,2023-04-03,2023-05-03,Sécheresse,SEC,Simple,IOME2308745A,Reconnue,182,2022,1,1
290237,13055,MARSEILLE,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1

In [32]:
df_drought_yearly.columns

Index(['insee', 'nom_commune', 'debut_evenement', 'fin_evenement',
       'date_arrete', 'date_parution_jo', 'nom_peril', 'code_peril',
       'franchise', 'code_nor', 'decision', 'event_length_days', 'year',
       'year_count', 'year_duration'],
      dtype='object')

In [33]:
df_new_insee['new_insee'].unique()

array(['79049', '59183', '62473', '13207', '13203', '13211', '13204',
       '13215', '13201', '13210', '13208', '13205', '13212', '13214',
       '13202', '13209', '13213', '13206', '13216'], dtype=object)

In [34]:
df_drought_yearly[df_drought_yearly['insee'].isin(df_new_insee['new_insee'].unique())]

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration
68349,59183,DUNKERQUE,1990-01-01,1990-12-31,1991-08-12,1991-08-30,Sécheresse,SEC,Simple,INTE9100354A,Reconnue,364,1990,1,1
68446,79049,BRESSUIRE,1989-05-01,1990-12-31,1991-08-12,1991-08-30,Sécheresse,SEC,Simple,INTE9100354A,Reconnue,609,1989,1,2
68446,79049,BRESSUIRE,1989-05-01,1990-12-31,1991-08-12,1991-08-30,Sécheresse,SEC,Simple,INTE9100354A,Reconnue,609,1990,2,2
69180,62473,ISBERGUES,1989-05-01,1990-12-31,1992-01-14,1992-02-05,Sécheresse,SEC,Simple,INTX9210012A,Reconnue,609,1989,1,2
69180,62473,ISBERGUES,1989-05-01,1990-12-31,1992-01-14,1992-02-05,Sécheresse,SEC,Simple,INTX9210012A,Reconnue,609,1990,2,2
76749,59183,DUNKERQUE,1992-01-01,1992-12-31,1994-06-30,1994-07-09,Sécheresse,SEC,Simple,INTE9400331A,Reconnue,365,1992,1,1
77097,59183,DUNKERQUE,1991-01-01,1992-09-30,1993-08-16,1993-09-03,Sécheresse,SEC,Simple,INTE9300372A,Reconnue,638,1991,1,2
77097,59183,DUNKERQUE,1991-01-01,1992-09-30,1993-08-16,1993-09-03,Sécheresse,SEC,Simple,INTE9300372A,Reconnue,638,1992,2,2
87941,59183,DUNKERQUE,1993-01-01,1993-09-30,1995-07-28,1995-09-09,Sécheresse,SEC,Simple,INTE9500338A,Reconnue,272,1993,1,1
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1991,1,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1992,2,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1993,3,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1994,4,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1995,5,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1996,6,7
97921,62473,ISBERGUES,1991-01-01,1997-01-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2222,1997,7,7
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1991,1,6
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1992,2,6
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1993,3,6
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1994,4,6
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1995,5,6
98138,79049,BRESSUIRE,1991-01-01,1996-10-31,1998-03-12,1998-03-28,Sécheresse,SEC,Simple,INTE9800067A,Reconnue,2130,1996,6,6
98540,59183,DUNKERQUE,1993-10-01,1996-12-31,1997-09-19,1997-10-11,Sécheresse,SEC,Simple,INTE9700395A,Reconnue,1187,1993,1,4
98540,59183,DUNKERQUE,1993-10-01,1996-12-31,1997-09-19,1997-10-11,Sécheresse,SEC,Simple,INTE9700395A,Reconnue,1187,1994,2,4
98540,59183,DUNKERQUE,1993-10-01,1996-12-31,1997-09-19,1997-10-11,Sécheresse,SEC,Simple,INTE9700395A,Reconnue,1187,1995,3,4
98540,59183,DUNKERQUE,1993-10-01,1996-12-31,1997-09-19,1997-10-11,Sécheresse,SEC,Simple,INTE9700395A,Reconnue,1187,1996,4,4
101237,59183,DUNKERQUE,1993-01-01,1997-12-31,1998-11-19,1998-12-11,Sécheresse,SEC,Simple,INTE9800443A,Reconnue,1825,1993,1,5
101237,59183,DUNKERQUE,1993-01-01,1997-12-31,1998-11-19,1998-12-11,Sécheresse,SEC,Simple,INTE9800443A,Reconnue,1825,1994,2,5
101237,59183,DUNKERQUE,1993-01-01,1997-12-31,1998-11-19,1998-12-11,Sécheresse,SEC,Simple,INTE9800443A,Reconnue,1825,1995,3,5
101237,59183,DUNKERQUE,1993-01-01,1997-12-31,1998-11-19,1998-12-11,Sécheresse,SEC,Simple,INTE9800443A,Reconnue,1825,1996,4,5
101237,59183,DUNKERQUE,1993-01-01,1997-12-31,1998-11-19,1998-12-11,Sécheresse,SEC,Simple,INTE9800443A,Reconnue,1825,1997,5,5
102745,79049,BRESSUIRE,1996-11-01,1998-08-31,1999-02-23,1999-03-10,Sécheresse,SEC,Simple,INTE9900087A,Reconnue,668,1996,1,3
102745,79049,BRESSUIRE,1996-11-01,1998-08-31,1999-02-23,1999-03-10,Sécheresse,SEC,Simple,INTE9900087A,Reconnue,668,1997,2,3
102745,79049,BRESSUIRE,1996-11-01,1998-08-31,1999-02-23,1999-03-10,Sécheresse,SEC,Simple,INTE9900087A,Reconnue,668,1998,3,3
181453,79049,BRESSUIRE,2003-07-01,2003-09-30,2005-11-22,2005-12-13,Sécheresse,SEC,Simple,INTE0500808A,Reconnue,91,2003,1,1
192931,79049,BRESSUIRE,2006-01-01,2006-03-31,2008-04-18,2008-04-23,Sécheresse,SEC,Triplée,IOCE0810063A,Reconnue,89,2006,1,1
192932,79049,BRESSUIRE,2005-07-01,2005-09-30,2008-04-18,2008-04-23,Sécheresse,SEC,Simple,IOCE0810063A,Reconnue,91,2005,1,1
210985,59183,DUNKERQUE,2009-07-01,2009-09-30,2010-12-13,2011-01-13,Sécheresse,SEC,Simple,IOCE1032143A,Reconnue,91,2009,1,1
217157,79049,BRESSUIRE,2011-04-01,2011-06-30,2012-07-11,2012-07-17,Sécheresse,SEC,Doublée,INTE1228647A,Reconnue,90,2011,1,1
219429,59183,DUNKERQUE,2011-04-01,2011-06-30,2012-10-18,2012-10-21,Sécheresse,SEC,Simple,INTE1236522A,Reconnue,90,2011,1,1
245480,79049,BRESSUIRE,2017-01-01,2017-12-31,2018-09-18,2018-10-20,Sécheresse,SEC,Simple,INTE1824834A,Reconnue,364,2017,1,1
254087,59183,DUNKERQUE,2018-10-01,2018-12-31,2019-11-19,2019-11-30,Sécheresse,SEC,Simple,INTE1932509A,Reconnue,91,2018,1,1
271749,62473,ISBERGUES,2020-04-01,2020-06-30,2021-12-21,2022-01-14,Sécheresse,SEC,Simple,INTE2137451A,Reconnue,90,2020,1,1
277973,59183,DUNKERQUE,2022-01-01,2022-03-31,2023-04-03,2023-05-03,Sécheresse,SEC,Simple,IOME2308745A,Reconnue,89,2022,1,1
278132,62473,ISBERGUES,2022-04-01,2022-09-30,2023-04-03,2023-05-03,Sécheresse,SEC,Simple,IOME2308745A,Reconnue,182,2022,1,1
278513,79049,BRESSUIRE,2022-04-01,2022-09-30,2023-04-03,2023-05-03,Sécheresse,SEC,Simple,IOME2308745A,Reconnue,182,2022,1,1

In [35]:
df_new_insee.columns

Index(['insee', 'nom_commune', 'new_insee', 'new_commune'], dtype='object')

In [36]:
# Function to update df_drought_yearly with new INSEE codes and commune names without modifying original dataframe
def update_drought_dataframe(df_drought_yearly, df_new_insee):
    # Create a copy of df_drought_yearly to ensure the original is not modified
    df_drought_yearly_copy = df_drought_yearly.copy()
    
    # Merge df_drought_yearly_copy with df_new_insee on 'insee' column, allowing duplicates to be created when there are multiple new entries
    df_merged = df_drought_yearly_copy.merge(df_new_insee, on=['insee', 'nom_commune'], how='left')

    # Initialize the 'old_insee' and 'old_commune' columns with 'unchanged'
    df_merged['old_insee'] = 'unchanged'
    df_merged['old_commune'] = 'unchanged'

    # Update the old_insee and old_commune before replacement
    df_merged.loc[pd.notna(df_merged['new_insee']), 'old_insee'] = df_merged['insee']
    df_merged.loc[pd.notna(df_merged['new_commune']), 'old_commune'] = df_merged['nom_commune']

    # Update the columns for new INSEE and new commune if they exist, otherwise keep the original
    df_merged['insee'] = df_merged.apply(lambda x: x['new_insee'] if pd.notna(x['new_insee']) else x['insee'], axis=1)
    df_merged['nom_commune'] = df_merged.apply(lambda x: x['new_commune'] if pd.notna(x['new_commune']) else x['nom_commune'], axis=1)
    
    # Drop unnecessary columns from the merge
    df_drought_yearly_new_insee = df_merged.drop(columns=['new_insee', 'new_commune'])
    
    return df_drought_yearly_new_insee

In [37]:
df_drought_yearly_new_insee = update_drought_dataframe(df_drought_yearly, df_new_insee)
df_drought_yearly_new_insee.head()

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration,old_insee,old_commune
0,12018,BALAGUIER D OLT,1990-01-01,1990-09-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,272,1990,1,1,unchanged,unchanged
1,12018,BALAGUIER D OLT,1992-03-01,1992-06-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,121,1992,1,1,unchanged,unchanged
2,17118,CORIGNAC,1989-05-01,1989-12-31,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,244,1989,1,1,unchanged,unchanged
3,17203,LANDRAIS,1990-01-01,1990-09-30,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,272,1990,1,1,unchanged,unchanged
4,17260,NEUVICQ,1989-05-01,1989-12-31,2001-11-15,2001-12-01,Sécheresse,SEC,Simple,INTE0100649A,Reconnue,244,1989,1,1,unchanged,unchanged

In [38]:
df_drought_yearly.columns.tolist()

['insee',
 'nom_commune',
 'debut_evenement',
 'fin_evenement',
 'date_arrete',
 'date_parution_jo',
 'nom_peril',
 'code_peril',
 'franchise',
 'code_nor',
 'decision',
 'event_length_days',
 'year',
 'year_count',
 'year_duration']

In [39]:
# Find the rows that are in df_drought_yearly but not in df_drought_yearly_new_insee
merged = df_drought_yearly.merge(df_drought_yearly_new_insee, on=df_drought_yearly.columns.tolist(), how='left', indicator=True)
rows_only_in_original = merged[merged['_merge'] == 'left_only']

# Print the rows that are only in df_drought_yearly
print(rows_only_in_original[df_drought_yearly.columns.tolist()])

       insee        nom_commune debut_evenement fin_evenement date_arrete  \
3589   79065        CHAMBROUTET      1989-05-01    1990-12-31  1991-12-04
3590   79065        CHAMBROUTET      1989-05-01    1990-12-31  1991-12-04
4255   59248       FORT MARDYCK      1990-01-01    1991-12-31  1992-07-31
4256   59248       FORT MARDYCK      1990-01-01    1991-12-31  1992-07-31
5651   13055          MARSEILLE      1989-05-01    1991-12-31  1993-01-25
5652   13055          MARSEILLE      1989-05-01    1991-12-31  1993-01-25
5653   13055          MARSEILLE      1989-05-01    1991-12-31  1993-01-25
6165   62575          MOLINGHEM      1991-01-01    1991-12-31  1993-01-25
11941  59248       FORT MARDYCK      1992-01-01    1993-12-31  1996-02-02
11942  59248       FORT MARDYCK      1992-01-01    1993-12-31  1996-02-02
16624  59540  SAINT POL SUR MER      1995-01-01    1997-06-30  1998-03-12
16625  59540  SAINT POL SUR MER      1995-01-01    1997-06-30  1998-03-12
16626  59540  SAINT POL SUR MER      1995-01-01    1997-06-30  1998-03-12
30382  13055          MARSEILLE      1992-01-01    1993-06-30  2000-12-27
30383  13055          MARSEILLE      1992-01-01    1993-06-30  2000-12-27
30384  13055          MARSEILLE      1998-01-01    1998-06-30  2000-12-27
31346  59248       FORT MARDYCK      1996-01-01    1996-12-31  2001-12-27
32555  13055          MARSEILLE      2002-01-01    2002-06-30  2004-08-25
39225  13055          MARSEILLE      2004-01-01    2004-03-31  2008-06-11
39226  13055          MARSEILLE      2005-01-01    2005-03-31  2008-06-11
39227  13055          MARSEILLE      2006-01-01    2006-03-31  2008-06-11
39471  13055          MARSEILLE      2007-01-01    2007-03-31  2008-08-07
39472  13055          MARSEILLE      2007-07-01    2007-09-30  2008-08-07
40044  13055          MARSEILLE      2008-01-01    2008-03-31  2009-10-16
44310  13055          MARSEILLE      2016-07-01    2016-09-30  2017-07-25
45413  13055          MARSEILLE      2017-07-01    2017-09-30  2018-07-10
53434  13055          MARSEILLE      2019-07-01    2019-09-30  2020-07-28
57469  13055          MARSEILLE      2022-04-01    2022-09-30  2023-04-03
64026  13055          MARSEILLE      2023-04-01    2023-06-30  2024-06-18

      date_parution_jo   nom_peril code_peril   franchise      code_nor  \
3589        1991-12-27  Sécheresse        SEC      Simple  INTX9110334A
3590        1991-12-27  Sécheresse        SEC      Simple  INTX9110334A
4255        1992-08-18  Sécheresse        SEC      Simple  INTX9210277A
4256        1992-08-18  Sécheresse        SEC      Simple  INTX9210277A
5651        1993-02-07  Sécheresse        SEC      Simple  INTE9300001A
5652        1993-02-07  Sécheresse        SEC      Simple  INTE9300001A
5653        1993-02-07  Sécheresse        SEC      Simple  INTE9300001A
6165        1993-02-07  Sécheresse        SEC      Simple  INTE9300001A
11941       1996-02-14  Sécheresse        SEC      Simple  INTE9600039A
11942       1996-02-14  Sécheresse        SEC      Simple  INTE9600039A
16624       1998-03-28  Sécheresse        SEC      Simple  INTE9800067A
16625       1998-03-28  Sécheresse        SEC      Simple  INTE9800067A
16626       1998-03-28  Sécheresse        SEC      Simple  INTE9800067A
30382       2000-12-29  Sécheresse        SEC      Simple  INTE0000771A
30383       2000-12-29  Sécheresse        SEC      Simple  INTE0000771A
30384       2000-12-29  Sécheresse        SEC      Simple  INTE0000771A
31346       2002-01-18  Sécheresse        SEC      Simple  INTE0100760A
32555       2004-08-26  Sécheresse        SEC     Doublée  INTE0400656A
39225       2008-06-14  Sécheresse        SEC      Simple  IOCE0814202A
39226       2008-06-14  Sécheresse        SEC      Simple  IOCE0814202A
39227       2008-06-14  Sécheresse        SEC      Simple  IOCE0814202A
39471       2008-08-13  Sécheresse        SEC      Simple  IOCE0819658A
39472       2008-08-13  Sécheresse        SEC      Simple  IOCE0819658A
40044       2009-10-21  Sécheresse        SEC  Quadruplée  IOCE0924280A
44310       2017-09-01  Sécheresse        SEC      Simple  INTE1719708A
45413       2018-07-27  Sécheresse        SEC      Simple  INTE1818803A
53434       2020-09-03  Sécheresse        SEC      Simple  INTE2019261A
57469       2023-05-03  Sécheresse        SEC      Simple  IOME2308745A
64026       2024-07-02  Sécheresse        SEC      Simple  IOME2415881A

       decision  event_length_days  year  year_count  year_duration
3589   Reconnue                609  1989           1              2
3590   Reconnue                609  1990           2              2
4255   Reconnue                729  1990           1              2
4256   Reconnue                729  1991           2              2
5651   Reconnue                974  1989           1              3
5652   Reconnue                974  1990           2              3
5653   Reconnue                974  1991           3              3
6165   Reconnue                364  1991           1              1
11941  Reconnue                730  1992           1              2
11942  Reconnue                730  1993           2              2
16624  Reconnue                911  1995           1              3
16625  Reconnue                911  1996           2              3
16626  Reconnue                911  1997           3              3
30382  Reconnue                546  1992           1              2
30383  Reconnue                546  1993           2              2
30384  Reconnue                180  1998           1              1
31346  Reconnue                365  1996           1              1
32555  Reconnue                180  2002           1              1
39225  Reconnue                 90  2004           1              1
39226  Reconnue                 89  2005           1              1
39227  Reconnue                 89  2006           1              1
39471  Reconnue                 89  2007           1              1
39472  Reconnue                 91  2007           1              1
40044  Reconnue                 90  2008           1              1
44310  Reconnue                 91  2016           1              1
45413  Reconnue                 91  2017           1              1
53434  Reconnue                 91  2019           1              1
57469  Reconnue                182  2022           1              1
64026  Reconnue                 90  2023           1              1

In [40]:
# Find the rows that are in df_drought_yearly but not in df_drought_yearly_new_insee
merged = df_drought_yearly_new_insee.merge(df_drought_yearly, on=df_drought_yearly.columns.tolist(), how='left', indicator=True)
rows_only_in_original = merged[merged['_merge'] == 'left_only']

# Print the rows that are only in df_drought_yearly
print(rows_only_in_original[df_drought_yearly.columns.tolist()])

       insee                    nom_commune debut_evenement fin_evenement  \
3589   79049                      BRESSUIRE      1989-05-01    1990-12-31
3590   79049                      BRESSUIRE      1989-05-01    1990-12-31
4255   59183                      DUNKERQUE      1990-01-01    1991-12-31
4256   59183                      DUNKERQUE      1990-01-01    1991-12-31
5651   13207  MARSEILLE--7E--ARRONDISSEMENT      1989-05-01    1991-12-31
...      ...                            ...             ...           ...
64292  13202  MARSEILLE--2E--ARRONDISSEMENT      2023-04-01    2023-06-30
64293  13209  MARSEILLE--9E--ARRONDISSEMENT      2023-04-01    2023-06-30
64294  13213  MARSEILLE-13E--ARRONDISSEMENT      2023-04-01    2023-06-30
64295  13206  MARSEILLE--6E--ARRONDISSEMENT      2023-04-01    2023-06-30
64296  13216  MARSEILLE-16E--ARRONDISSEMENT      2023-04-01    2023-06-30

      date_arrete date_parution_jo   nom_peril code_peril franchise  \
3589   1991-12-04       1991-12-27  Sécheresse        SEC    Simple
3590   1991-12-04       1991-12-27  Sécheresse        SEC    Simple
4255   1992-07-31       1992-08-18  Sécheresse        SEC    Simple
4256   1992-07-31       1992-08-18  Sécheresse        SEC    Simple
5651   1993-01-25       1993-02-07  Sécheresse        SEC    Simple
...           ...              ...         ...        ...       ...
64292  2024-06-18       2024-07-02  Sécheresse        SEC    Simple
64293  2024-06-18       2024-07-02  Sécheresse        SEC    Simple
64294  2024-06-18       2024-07-02  Sécheresse        SEC    Simple
64295  2024-06-18       2024-07-02  Sécheresse        SEC    Simple
64296  2024-06-18       2024-07-02  Sécheresse        SEC    Simple

           code_nor  decision  event_length_days  year  year_count  \
3589   INTX9110334A  Reconnue                609  1989           1
3590   INTX9110334A  Reconnue                609  1990           2
4255   INTX9210277A  Reconnue                729  1990           1
4256   INTX9210277A  Reconnue                729  1991           2
5651   INTE9300001A  Reconnue                974  1989           1
...             ...       ...                ...   ...         ...
64292  IOME2415881A  Reconnue                 90  2023           1
64293  IOME2415881A  Reconnue                 90  2023           1
64294  IOME2415881A  Reconnue                 90  2023           1
64295  IOME2415881A  Reconnue                 90  2023           1
64296  IOME2415881A  Reconnue                 90  2023           1

       year_duration
3589               2
3590               2
4255               2
4256               2
5651               3
...              ...
64292              1
64293              1
64294              1
64295              1
64296              1

[299 rows x 15 columns]

In [41]:
df_drought_yearly_new_insee[df_drought_yearly_new_insee['old_commune']=='MARSEILLE']

,insee,nom_commune,debut_evenement,fin_evenement,date_arrete,date_parution_jo,nom_peril,code_peril,franchise,code_nor,decision,event_length_days,year,year_count,year_duration,old_insee,old_commune
5651,13207,MARSEILLE--7E--ARRONDISSEMENT,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3,13055,MARSEILLE
5652,13203,MARSEILLE--3E--ARRONDISSEMENT,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3,13055,MARSEILLE
5653,13211,MARSEILLE-11E--ARRONDISSEMENT,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3,13055,MARSEILLE
5654,13204,MARSEILLE--4E--ARRONDISSEMENT,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3,13055,MARSEILLE
5655,13215,MARSEILLE-15E--ARRONDISSEMENT,1989-05-01,1991-12-31,1993-01-25,1993-02-07,Sécheresse,SEC,Simple,INTE9300001A,Reconnue,974,1989,1,3,13055,MARSEILLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64292,13202,MARSEILLE--2E--ARRONDISSEMENT,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1,13055,MARSEILLE
64293,13209,MARSEILLE--9E--ARRONDISSEMENT,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1,13055,MARSEILLE
64294,13213,MARSEILLE-13E--ARRONDISSEMENT,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1,13055,MARSEILLE
64295,13206,MARSEILLE--6E--ARRONDISSEMENT,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1,13055,MARSEILLE
64296,13216,MARSEILLE-16E--ARRONDISSEMENT,2023-04-01,2023-06-30,2024-06-18,2024-07-02,Sécheresse,SEC,Simple,IOME2415881A,Reconnue,90,2023,1,1,13055,MARSEILLE

In [42]:
df_drought_yearly.columns

Index(['insee', 'nom_commune', 'debut_evenement', 'fin_evenement',
       'date_arrete', 'date_parution_jo', 'nom_peril', 'code_peril',
       'franchise', 'code_nor', 'decision', 'event_length_days', 'year',
       'year_count', 'year_duration'],
      dtype='object')

In [43]:
df_drought_yearly[df_drought_yearly['nom_commune']=='MARSEILLE'].shape

(18, 15)

In [44]:
18*16

288

In [45]:
df_drought_yearly_new_insee['old_commune'].unique()

array(['unchanged', 'CHAMBROUTET', 'FORT MARDYCK', 'MARSEILLE',
       'MOLINGHEM', 'SAINT POL SUR MER'], dtype=object)

In [46]:
df_drought_yearly.shape

(64713, 15)

In [47]:
df_drought_yearly_new_insee.shape

(64983, 17)

In [48]:
64983-64713

270

In [49]:
df_drought_yearly_new_insee.isna().sum()

insee                0
nom_commune          0
debut_evenement      0
fin_evenement        0
date_arrete          0
date_parution_jo     0
nom_peril            0
code_peril           0
franchise            0
code_nor             0
decision             0
event_length_days    0
year                 0
year_count           0
year_duration        0
old_insee            0
old_commune          0
dtype: int64

In [50]:
def check_insee_coverage(df1, df2, insee_col1, insee_col2):
    # Step 1: Create copies of the dataframes to avoid modifying the input dataframes
    df1_copy = df1.copy()
    df2_copy = df2.copy()

    # Step 2: Remove spaces before and after in the INSEE code columns and remove leading zeros to ensure proper comparison
    df1_copy[insee_col1] = df1_copy[insee_col1].str.strip().str.lstrip('0')
    df2_copy[insee_col2] = df2_copy[insee_col2].str.strip().str.lstrip('0')

    # Step 3: Get the list of INSEE codes from df2
    insee_codes_df2 = df2_copy[insee_col2].unique()

    # Step 4: Check if all INSEE codes in df1 are present in df2
    all_in_df2 = df1_copy[insee_col1].isin(insee_codes_df2)

    # Step 5: Return the communes in df1 that are not in df2
    missing_communes = df1_copy[~all_in_df2]
    return missing_communes

# Example usage of the function
missing_communesII = check_insee_coverage(df_drought_yearly_new_insee, df_communes_location, 'insee', 'Code INSEE')
print(missing_communesII[['insee', 'nom_commune']])

Empty DataFrame
Columns: [insee, nom_commune]
Index: []

In [51]:
df_communes_location.columns

Index(['Code INSEE', 'Code Postal', 'Commune', 'Département', 'Région',
       'Statut', 'Altitude Moyenne', 'Superficie', 'Population',
       'geo_point_2d', 'geo_shape', 'ID Geofla', 'Code Commune', 'Code Canton',
       'Code Arrondissement', 'Code Département', 'Code Région'],
      dtype='object')

In [52]:
df_drought_yearly_new_insee.columns

Index(['insee', 'nom_commune', 'debut_evenement', 'fin_evenement',
       'date_arrete', 'date_parution_jo', 'nom_peril', 'code_peril',
       'franchise', 'code_nor', 'decision', 'event_length_days', 'year',
       'year_count', 'year_duration', 'old_insee', 'old_commune'],
      dtype='object')

In [53]:
df_drought_yearly_new_insee.shape

(64983, 17)

In [54]:
def merge_communes_drought(df_communes_location, df_drought_yearly_new_insee):
    # Make copies of input dataframes to avoid modifying original data
    df_communes_location_copy = df_communes_location.copy()
    df_drought_yearly_new_insee_copy = df_drought_yearly_new_insee.copy()
    
    # Clean and prepare the 'Code INSEE' and 'insee' columns
    df_communes_location_copy['Code INSEE'] = df_communes_location_copy['Code INSEE'].astype(str).str.strip().str.lstrip('0')
    df_drought_yearly_new_insee_copy['insee'] = df_drought_yearly_new_insee_copy['insee'].astype(str).str.strip().str.lstrip('0')
    
    # Split latitude and longitude from 'geo_point_2d' in df_communes_location
    df_communes_location_copy[['latitude', 'longitude']] = df_communes_location_copy['geo_point_2d'].str.split(',', expand=True)
    
    # Merge dataframes with a full join on 'Code INSEE' and 'insee'
    df_communes_drought = pd.merge(df_communes_location_copy, df_drought_yearly_new_insee_copy, 
                                   left_on='Code INSEE', right_on='insee', 
                                   how='outer', 
                                   suffixes=('_location', '_drought'))
    
    # Decide which 'nom_commune' and 'insee' to retain (prioritizing location data if available)
    df_communes_drought['insee'] = df_communes_drought['Code INSEE'].combine_first(df_communes_drought['insee'])
    df_communes_drought['nom_commune'] = df_communes_drought['Commune'].combine_first(df_communes_drought['nom_commune'])
    
    # Select desired columns
    df_communes_drought = df_communes_drought[['insee', 'nom_commune', 'latitude', 'longitude', 'year', 'decision', 
                                               'Code Postal', 'Département', 'Région', 
                                               'Code Département', 'Code Région']]
    
    return df_communes_drought

# Example usage:
# df_result = merge_communes_drought(df_communes_location, df_drought_yearly_new_insee)

In [55]:
# Example usage:
df_communes_drought = merge_communes_drought(df_communes_location, df_drought_yearly_new_insee)

In [56]:
df_communes_drought

,insee,nom_commune,latitude,longitude,year,decision,Code Postal,Département,Région,Code Département,Code Région
0,10002,AILLEVILLE,48.254999570440795,4.694493292675681,NaN,NaN,10200,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
1,10003,AIX-EN-OTHE,48.197574577142234,3.736327941130472,NaN,NaN,10160,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
2,10004,ALLIBAUDIERES,48.58639979643813,4.122927712355601,NaN,NaN,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
3,10005,AMANCE,48.291854073583025,4.487048921603067,NaN,NaN,10140,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
4,10006,ARCIS-SUR-AUBE,48.52782710690875,4.141971102479263,NaN,NaN,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
...,...,...,...,...,...,...,...,...,...,...,...
87301,97613,M'TSANGAMOUJI,-12.751309930876255,45.08716968710385,NaN,NaN,97650,['MAYOTTE'],['MAYOTTE'],97,6
87302,97614,OUANGANI,-12.837095519562995,45.13790954970948,NaN,NaN,97670,['MAYOTTE'],['MAYOTTE'],97,6
87303,97615,PAMANDZI,-12.79613533089382,45.284206310217414,NaN,NaN,97610,['MAYOTTE'],['MAYOTTE'],97,6
87304,97616,SADA,-12.861164960856163,45.11855031452601,NaN,NaN,97640,['MAYOTTE'],['MAYOTTE'],97,6
87305,97617,TSINGONI,-12.782166673603141,45.13442790826678,NaN,NaN,97680,['MAYOTTE'],['MAYOTTE'],97,6

In [57]:
df_communes_drought['insee'].describe()

count     87306
unique    36742
top       31555
freq         49
Name: insee, dtype: object

In [58]:
df_communes_drought.isna().sum()

insee                   0
nom_commune             0
latitude                0
longitude               0
year                22323
decision            22323
Code Postal             0
Département             0
Région                  0
Code Département        0
Code Région             0
dtype: int64

In [59]:
df_communes_drought.year.describe()

count    64983.000000
mean      2004.023021
std         12.148492
min       1988.000000
25%       1993.000000
50%       2002.000000
75%       2018.000000
max       2023.000000
Name: year, dtype: float64

In [60]:
import pandas as pd
import numpy as np

def clean_communes_drought(df_communes_drought, start_year=2000):
    # Make a copy of the input dataframe to avoid modifying the original data
    df_communes_drought_clean = df_communes_drought.copy()
    
    ##remove nas cause above, for some reason, I did a full join
    ##df_communes_drought_clean.dropna(inplace=True)
    
    # Step 1: Set start_year to be between min_year and max_year, or min_year if out of range
    max_year = df_communes_drought_clean['year'].max()
    min_year = df_communes_drought_clean['year'].min()
    if start_year < min_year or start_year > max_year:
        start_year = min_year
    
    # Step 2: Fill NaN values in 'year' with start_year and convert to integer
    df_communes_drought_clean['year'] = df_communes_drought_clean['year'].fillna(start_year).astype(int)
    
    # Step 3: Replace NaN values in 'decision' column with 0
    df_communes_drought_clean['decision'] = df_communes_drought_clean['decision'].apply(lambda x: 1 if x == 'Reconnue' else 0).fillna(0).astype(int)
    
    # Step 4: Keep only rows with year >= start_year
    df_communes_drought_clean = df_communes_drought_clean[df_communes_drought_clean['year'] >= start_year]
    
    # Step 5: For every 'insee', duplicate lines for every missing year between start_year and max_year with decision set to 0
    all_years = pd.Series(range(int(start_year), int(max_year) + 1))
    
    # Group by INSEE and generate the missing years only for that INSEE
    all_rows = []
    for insee, group in df_communes_drought_clean.groupby('insee'):
        years_present = group['year']
        missing_years = all_years[~all_years.isin(years_present)]
        
        # Append the original group
        all_rows.append(group)
        
        # Add missing years with decision set to 0
        if not missing_years.empty:
            missing_rows = group.iloc[0:1].copy()
            missing_rows = missing_rows.loc[missing_rows.index.repeat(len(missing_years))]
            missing_rows['year'] = missing_years.values
            missing_rows['decision'] = 0
            all_rows.append(missing_rows)

    df_communes_drought_clean = pd.concat(all_rows, ignore_index=True)

    # Step 6: Sort the cleaned dataframe by 'insee', 'nom_commune', 'latitude', 'longitude', 'year', 'decision'
    df_communes_drought_clean = df_communes_drought_clean.sort_values(by=['insee', 'nom_commune', 'latitude', 'longitude', 'year', 'decision'])

    return df_communes_drought_clean

# Example usage:
# df_cleaned = clean_communes_drought(df_communes_drought, start_year=2000)
# import ace_tools as tools; tools.display_dataframe_to_user(name="Cleaned Communes Drought Dataframe", dataframe=df_cleaned)

In [61]:
df_communes_drought_cleaned = clean_communes_drought(df_communes_drought, start_year=2000)

In [62]:
df_communes_drought_cleaned.shape

(866884, 11)

In [63]:
df_drought_yearly.shape

(64713, 15)

In [64]:
# Create a small sample dataframe named df_test to verify the function
data = {
    'insee': [12018, 12018, 17118, 17203, 17260],
    'nom_commune': ['BALAGUIER D OLT', 'BALAGUIER D OLT', 'CORIGNAC', 'LANDRAIS', 'NEUVICQ'],
    'debut_evenement': ['1990-01-01', '1992-03-01', '1989-05-01', '1990-01-01', '1989-05-01'],
    'fin_evenement': ['1990-09-30', '1992-06-30', '1989-12-31', '1990-09-30', '1989-12-31'],
    'date_arrete': ['2001-11-15', '2001-11-15', '2001-11-15', '2001-11-15', '2001-11-15'],
    'date_parution_jo': ['2001-12-01', '2001-12-01', '2001-12-01', '2001-12-01', '2001-12-01'],
    'nom_peril': ['Sécheresse', 'Sécheresse', 'Sécheresse', 'Sécheresse', 'Sécheresse'],
    'code_peril': ['SEC', 'SEC', 'SEC', 'SEC', 'SEC'],
    'franchise': ['Simple', 'Simple', 'Simple', 'Simple', 'Simple'],
    'code_nor': ['INTE0100649A', 'INTE0100649A', 'INTE0100649A', 'INTE0100649A', 'INTE0100649A'],
    'decision': ['Reconnue', 'Reconnue', 'Reconnue', None, 'Reconnue'],
    'event_length_days': [272, 121, 244, 272, 244],
    'year': [1990, 1992, 1989, None, 1989],
    'year_count': [1, 1, 1, 1, 1],
    'year_duration': [1, 1, 1, 1, 1],
    'latitude': [44.5136, 44.5136, 45.3488, 45.4532, 45.5637],
    'longitude': [1.9262, 1.9262, -0.4013, -0.9502, -0.6803],
    'Code Postal': [12345, 12345, 67890, 67891, 67892],
    'Commune': ['BALAGUIER', 'BALAGUIER', 'CORIGNAC', 'LANDRAIS', 'NEUVICQ'],
    'Département': ['Aveyron', 'Aveyron', 'Charente', 'Charente-Maritime', 'Charente-Maritime'],
    'Région': ['Occitanie', 'Occitanie', 'Nouvelle-Aquitaine', 'Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'],
    'Code Département': [12, 12, 16, 17, 17],
    'Code Région': [76, 76, 75, 75, 75],
}

# Convert the data to a dataframe named df_test
df_test = pd.DataFrame(data)

# Call the function with the sample dataframe df_test and a start year of 1990
df_cleaned = clean_communes_drought(df_test, start_year=1990)

# Display the cleaned dataframe to verify the output
#import ace_tools as tools
#tools.display_dataframe_to_user(name="Cleaned Test Communes Drought Dataframe", dataframe=df_cleaned)

In [65]:
df_test.columns

Index(['insee', 'nom_commune', 'debut_evenement', 'fin_evenement',
       'date_arrete', 'date_parution_jo', 'nom_peril', 'code_peril',
       'franchise', 'code_nor', 'decision', 'event_length_days', 'year',
       'year_count', 'year_duration', 'latitude', 'longitude', 'Code Postal',
       'Commune', 'Département', 'Région', 'Code Département', 'Code Région'],
      dtype='object')

In [66]:
df_test[['insee', 'nom_commune', 'latitude', 'longitude', 'year', 'decision', 'Code Postal', 'Commune', 'Département', 'Région', 'Code Département', 'Code Région']]

,insee,nom_commune,latitude,longitude,year,decision,Code Postal,Commune,Département,Région,Code Département,Code Région
0,12018,BALAGUIER D OLT,44.5136,1.9262,1990.0,Reconnue,12345,BALAGUIER,Aveyron,Occitanie,12,76
1,12018,BALAGUIER D OLT,44.5136,1.9262,1992.0,Reconnue,12345,BALAGUIER,Aveyron,Occitanie,12,76
2,17118,CORIGNAC,45.3488,-0.4013,1989.0,Reconnue,67890,CORIGNAC,Charente,Nouvelle-Aquitaine,16,75
3,17203,LANDRAIS,45.4532,-0.9502,NaN,None,67891,LANDRAIS,Charente-Maritime,Nouvelle-Aquitaine,17,75
4,17260,NEUVICQ,45.5637,-0.6803,1989.0,Reconnue,67892,NEUVICQ,Charente-Maritime,Nouvelle-Aquitaine,17,75

In [67]:
df_cleaned[['insee', 'nom_commune', 'latitude', 'longitude', 'year', 'decision', 'Code Postal', 'Commune', 'Département', 'Région', 'Code Département', 'Code Région']]

,insee,nom_commune,latitude,longitude,year,decision,Code Postal,Commune,Département,Région,Code Département,Code Région
0,12018,BALAGUIER D OLT,44.5136,1.9262,1990,1,12345,BALAGUIER,Aveyron,Occitanie,12,76
2,12018,BALAGUIER D OLT,44.5136,1.9262,1991,0,12345,BALAGUIER,Aveyron,Occitanie,12,76
1,12018,BALAGUIER D OLT,44.5136,1.9262,1992,1,12345,BALAGUIER,Aveyron,Occitanie,12,76
3,17203,LANDRAIS,45.4532,-0.9502,1990,0,67891,LANDRAIS,Charente-Maritime,Nouvelle-Aquitaine,17,75
4,17203,LANDRAIS,45.4532,-0.9502,1991,0,67891,LANDRAIS,Charente-Maritime,Nouvelle-Aquitaine,17,75
5,17203,LANDRAIS,45.4532,-0.9502,1992,0,67891,LANDRAIS,Charente-Maritime,Nouvelle-Aquitaine,17,75

### Sort clean commune drought by year

In [68]:
df_communes_drought_cleaned = df_communes_drought_cleaned.sort_values(by=['year', 'insee', 'nom_commune', 'latitude', 'longitude', 'decision'])

### Merge drought outcome data to weather data

In [69]:
def filter_communes_within_weather_bounds(df_communes_drought_cleaned, df_yearly_weather, extend_km=25):
    """
    Filters df_communes_drought_cleaned to only include areas covered by df_yearly_weather based on latitude and longitude bounds,
    extended by approximately `extend_km` kilometers in each direction.
    Additionally, returns the part of df_communes_drought_cleaned that was excluded.
    
    Parameters:
    df_communes_drought_cleaned (pd.DataFrame): DataFrame containing commune drought data with 'latitude' and 'longitude' columns.
    df_yearly_weather (pd.DataFrame): DataFrame containing yearly weather data with 'latitude' and 'longitude' columns.
    extend_km (float, optional): Distance in kilometers to extend the boundaries by. Default is 25 km.
    
    Returns:
    tuple: A tuple containing two DataFrames:
        - A filtered copy of df_communes_drought_cleaned that is within the latitude and longitude bounds of df_yearly_weather.
        - A copy of df_communes_drought_cleaned that was excluded from the bounds.
    """
    # Ensure latitude and longitude columns are numeric
    df_communes_drought_cleaned['latitude'] = pd.to_numeric(df_communes_drought_cleaned['latitude'], errors='coerce')
    df_communes_drought_cleaned['longitude'] = pd.to_numeric(df_communes_drought_cleaned['longitude'], errors='coerce')
    df_yearly_weather['latitude'] = pd.to_numeric(df_yearly_weather['latitude'], errors='coerce')
    df_yearly_weather['longitude'] = pd.to_numeric(df_yearly_weather['longitude'], errors='coerce')
    
    # Drop rows with NaN values resulting from coercion
    df_communes_drought_cleaned = df_communes_drought_cleaned.dropna(subset=['latitude', 'longitude'])
    df_yearly_weather = df_yearly_weather.dropna(subset=['latitude', 'longitude'])
    
    # Get the min and max latitude and longitude from df_yearly_weather
    min_latitude = df_yearly_weather['latitude'].min()
    max_latitude = df_yearly_weather['latitude'].max()
    min_longitude = df_yearly_weather['longitude'].min()
    max_longitude = df_yearly_weather['longitude'].max()
    
    # Convert extend_km to degrees for latitude and longitude
    km_to_deg_lat = extend_km / 111  # 1 degree latitude is approximately 111 km
    km_to_deg_lon = extend_km / (111 * np.cos(np.deg2rad((min_latitude + max_latitude) / 2)))  # Adjust longitude degree based on latitude
    
    # Extend the boundaries
    min_latitude -= km_to_deg_lat
    max_latitude += km_to_deg_lat
    min_longitude -= km_to_deg_lon
    max_longitude += km_to_deg_lon
    
    # Filter df_communes_drought_cleaned to only include rows within the extended bounds
    filtered_df = df_communes_drought_cleaned[
        (df_communes_drought_cleaned['latitude'] >= min_latitude) &
        (df_communes_drought_cleaned['latitude'] <= max_latitude) &
        (df_communes_drought_cleaned['longitude'] >= min_longitude) &
        (df_communes_drought_cleaned['longitude'] <= max_longitude)
    ].copy()
    
    # Get the rows that are outside the bounds
    excluded_df = df_communes_drought_cleaned[
        ~((df_communes_drought_cleaned['latitude'] >= min_latitude) &
          (df_communes_drought_cleaned['latitude'] <= max_latitude) &
          (df_communes_drought_cleaned['longitude'] >= min_longitude) &
          (df_communes_drought_cleaned['longitude'] <= max_longitude))
    ].copy()
    
    return filtered_df, excluded_df

In [70]:
# Example usage:
filtered_communes, excluded_communes = filter_communes_within_weather_bounds(df_communes_drought_cleaned, df_yearly_weather, extend_km=25)
# map_result = plot_lat_lon_on_map(filtered_communes, excluded_communes)
# map_result.save("communes_map.html")

In [71]:
def plot_lat_lon_on_map(excluded_df=None, filtered_df=None):
    """
    Plots the unique latitudes and longitudes from the excluded DataFrame on a map using folium.
    Yellow pins represent excluded locations.
    If filtered DataFrame is provided, green pins represent filtered locations.
    
    Parameters:
    excluded_df (pd.DataFrame): DataFrame containing excluded commune drought data with 'latitude' and 'longitude' columns.
    filtered_df (pd.DataFrame, optional): DataFrame containing filtered commune drought data with 'latitude' and 'longitude' columns.
    
    Returns:
    folium.Map: A folium map with pins representing the locations of excluded and filtered DataFrames.
    """
    # Create a base map centered around the average latitude and longitude of excluded DataFrame if available
    if excluded_df is not None:
        unique_excluded = excluded_df[['latitude', 'longitude']].drop_duplicates()
        avg_lat = unique_excluded['latitude'].mean()
        avg_lon = unique_excluded['longitude'].mean()
    elif filtered_df is not None:
        unique_filtered = filtered_df[['latitude', 'longitude']].drop_duplicates()
        avg_lat = unique_filtered['latitude'].mean()
        avg_lon = unique_filtered['longitude'].mean()
    else:
        raise ValueError("At least one of excluded_df or filtered_df must be provided.")
    
    base_map = folium.Map(location=[avg_lat, avg_lon], zoom_start=6)
    
    # Plot excluded DataFrame locations in yellow if available
    if excluded_df is not None:
        unique_excluded = excluded_df[['latitude', 'longitude']].drop_duplicates()
        for _, row in unique_excluded.iterrows():
            folium.Marker(
                location=[row['latitude'], row['longitude']],
                icon=folium.Icon(color='yellow'),
                popup=f"Excluded: ({row['latitude']}, {row['longitude']})"
            ).add_to(base_map)
    
    # Optionally plot filtered DataFrame locations in green if provided
    if filtered_df is not None:
        unique_filtered = filtered_df[['latitude', 'longitude']].drop_duplicates()
        for _, row in unique_filtered.iterrows():
            folium.Marker(
                location=[row['latitude'], row['longitude']],
                icon=folium.Icon(color='green'),
                popup=f"Filtered: ({row['latitude']}, {row['longitude']})"
            ).add_to(base_map)
    
    return base_map

In [72]:
#Example usage:
# filtered_communes, excluded_communes = filter_communes_within_weather_bounds(df_communes_drought_cleaned, df_yearly_weather)
map_result = plot_lat_lon_on_map(excluded_df=excluded_communes)
#map_result.save("excluded_communes_map.html")

/tmp/ipykernel_1760913/817239893.py:34: UserWarning: color argument of Icon should be one of: {'cadetblue', 'darkgreen', 'purple', 'red', 'darkblue', 'gray', 'darkred', 'orange', 'pink', 'lightgray', 'green', 'lightgreen', 'darkpurple', 'lightblue', 'black', 'beige', 'white', 'lightred', 'blue'}.
  icon=folium.Icon(color='yellow'),

In [73]:
def merge_dataframes_by_year(df1_decrees, df2_weather):
    # Work with copies to avoid modifying the original DataFrames
    df1_decrees = df1_decrees.copy()
    df2_weather = df2_weather.copy()

    # Add suffixes to columns
    df1_decrees = df1_decrees.add_suffix('_1')
    df2_weather = df2_weather.add_suffix('_2')

    # Create new columns for radians
    df1_decrees['latitude_rad_1'] = np.radians(df1_decrees['latitude_1'])
    df1_decrees['longitude_rad_1'] = np.radians(df1_decrees['longitude_1'])
    df2_weather['latitude_rad_2'] = np.radians(df2_weather['latitude_2'])
    df2_weather['longitude_rad_2'] = np.radians(df2_weather['longitude_2'])

    # Ensure both DataFrames have a 'year' column
    if 'year_1' not in df1_decrees.columns or 'year_2' not in df2_weather.columns:
        raise ValueError("Both DataFrames must contain a 'year' column.")

    # Create an empty list to store the results for each year
    merged_data = []

    # Loop over each unique year in df1_decrees and df2_weather (we assume both DataFrames have similar years)
    for year in df1_decrees['year_1'].unique():
        # Filter df1_decrees and df2_weather by the current year
        df1_year = df1_decrees[df1_decrees['year_1'] == year].reset_index(drop=True)
        df2_year = df2_weather[df2_weather['year_2'] == year].reset_index(drop=True)
        
        # Skip if there's no matching data for the current year in df2_weather
        if df2_year.empty:
            print(f"No data available for year {year} in df2_weather.")
            continue
        
        # Create BallTree using df2_year's latitude and longitude in radians
        tree = BallTree(df2_year[['latitude_rad_2', 'longitude_rad_2']], metric='haversine')

        # Find the nearest neighbors in df2_year for each point in df1_year
        distances, indices = tree.query(df1_year[['latitude_rad_1', 'longitude_rad_1']], k=1)

        # Extract the nearest neighbors from df2_year using the indices
        df2_nearest = df2_year.iloc[indices.flatten()].reset_index(drop=True)

        # Reset df1_year index so we can concatenate the result with df2_nearest
        df1_reset = df1_year.reset_index(drop=True)

        # Concatenate the two DataFrames along with other columns from df1_year and df2_nearest
        df_merged_year = pd.concat([df1_reset, df2_nearest], axis=1)

        # Convert distances back to kilometers (since Haversine distance is in radians)
        earth_radius_km = 6371  # Radius of the Earth in kilometers
        df_merged_year['distance_km'] = distances.flatten() * earth_radius_km

        # Add this year's merged data to the list
        merged_data.append(df_merged_year)

    # Combine all the yearly merged data into a single DataFrame
    df_merged_final = pd.concat(merged_data, axis=0)

    return df_merged_final

# Example usage:
# df1_decrees = pd.DataFrame with 'latitude', 'longitude', 'temperature', 'humidity', 'year_of_measure', etc.
# df2_weather = pd.DataFrame with 'latitude', 'longitude', 'pressure', 'altitude', 'year_of_measure', etc.
# merged_df = merge_dataframes_by_year(df1_decrees, df2_weather)
# print(merged_df.head())

In [74]:
df_decrees_weather_communes_df = merge_dataframes_by_year(filtered_communes, df_yearly_weather)

In [75]:
df_decrees_weather_communes_df

,insee_1,nom_commune_1,latitude_1,longitude_1,year_1,decision_1,Code Postal_1,Département_1,Région_1,Code Département_1,...,stl2_mean_2,slt_sum_2,slt_mean_2,swvl1_sum_2,swvl1_mean_2,swvl2_sum_2,swvl2_mean_2,latitude_rad_2,longitude_rad_2,distance_km
0,10002,AILLEVILLE,48.255000,4.694493,2000,0,10200,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.360728,36.0,3.0,4.290780,0.357565,4.225537,0.352128,0.842121,0.082903,4.147094
1,10003,AIX-EN-OTHE,48.197575,3.736328,2000,0,10160,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.673390,24.0,2.0,4.221337,0.351778,4.156231,0.346353,0.842121,0.065450,5.916774
2,10004,ALLIBAUDIERES,48.586400,4.122928,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.781789,24.0,2.0,4.192894,0.349408,4.119763,0.343314,0.846485,0.069813,13.198245
3,10005,AMANCE,48.291854,4.487049,2000,0,10140,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.527883,24.0,2.0,4.238762,0.353230,4.164776,0.347065,0.842121,0.078540,4.751647
4,10006,ARCIS-SUR-AUBE,48.527827,4.141971,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.784230,24.0,2.0,4.209328,0.350777,4.135861,0.344655,0.846485,0.074176,8.537810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35607,95675,VILLERON,49.060843,2.534511,2023,0,95380,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.806976,24.0,2.0,3.870941,0.322578,3.820614,0.318384,0.855211,0.043633,7.218142
35608,95676,VILLERS-EN-ARTHIES,49.085900,1.730396,2023,0,95510,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.669118,24.0,2.0,3.961685,0.330140,3.880611,0.323384,0.855211,0.030543,9.657919
35609,95678,VILLIERS-ADAM,49.070289,2.239509,2023,0,95840,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.757823,24.0,2.0,3.926819,0.327235,3.863033,0.321919,0.855211,0.039270,7.853091
35610,95682,VILLIERS-LE-SEC,49.074309,2.386890,2023,0,95720,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.806976,24.0,2.0,3.870941,0.322578,3.820614,0.318384,0.855211,0.043633,11.672969
35611,95690,WY-DIT-JOLI-VILLAGE,49.095820,1.825029,2023,0,95420,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.669118,24.0,2.0,3.961685,0.330140,3.880611,0.323384,0.855211,0.030543,11.975907

In [76]:
map_result

### Save clean commune drought

In [77]:
# save to parquet
df_communes_drought_cleaned.to_parquet(os.path.join(processed_data_folder_name, drought_commune_clean_filename))

In [78]:
# Save the schema (data types) to a file
df_communes_drought_cleaned.dtypes.to_csv(os.path.join(processed_data_folder_name, drought_commune_clean_shema_filename))

## Test reloading

In [79]:
# test reloading the dataframe from parquet
import pandas as pd

df_reloaded = pd.read_parquet(os.path.join(processed_data_folder_name, drought_commune_clean_filename))

In [80]:
# Load the schema (data types) from the file
reloaded_schema = pd.read_csv(os.path.join(processed_data_folder_name, drought_commune_clean_shema_filename), index_col=0).squeeze("columns")

In [81]:
# Apply the schema to the loaded dataframe
df_reloaded = df_reloaded.astype(reloaded_schema.to_dict())

In [82]:
df_reloaded.equals(df_communes_drought_cleaned)

True

In [83]:
df_reloaded.shape

(866884, 11)

In [84]:
df_reloaded

,insee,nom_commune,latitude,longitude,year,decision,Code Postal,Département,Région,Code Département,Code Région
0,10002,AILLEVILLE,48.255000,4.694493,2000,0,10200,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
24,10003,AIX-EN-OTHE,48.197575,3.736328,2000,0,10160,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
48,10004,ALLIBAUDIERES,48.586400,4.122928,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
72,10005,AMANCE,48.291854,4.487049,2000,0,10140,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
96,10006,ARCIS-SUR-AUBE,48.527827,4.141971,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,21
...,...,...,...,...,...,...,...,...,...,...,...
866787,97613,M'TSANGAMOUJI,-12.751310,45.087170,2023,0,97650,['MAYOTTE'],['MAYOTTE'],97,6
866811,97614,OUANGANI,-12.837096,45.137910,2023,0,97670,['MAYOTTE'],['MAYOTTE'],97,6
866835,97615,PAMANDZI,-12.796135,45.284206,2023,0,97610,['MAYOTTE'],['MAYOTTE'],97,6
866859,97616,SADA,-12.861165,45.118550,2023,0,97640,['MAYOTTE'],['MAYOTTE'],97,6
866883,97617,TSINGONI,-12.782167,45.134428,2023,0,97680,['MAYOTTE'],['MAYOTTE'],97,6

### Save clean weather commune drought

In [85]:
# save to parquet
df_decrees_weather_communes_df.to_parquet(os.path.join(processed_data_folder_name, drought_weather_filename))

In [86]:
# Save the schema (data types) to a file
df_decrees_weather_communes_df.dtypes.to_csv(os.path.join(processed_data_folder_name, drought_weather_shema_filename))

## Test reloading

In [87]:
# test reloading the dataframe from parquet
import pandas as pd

df_reloaded = pd.read_parquet(os.path.join(processed_data_folder_name, drought_weather_filename))

In [88]:
# Load the schema (data types) from the file
reloaded_schema = pd.read_csv(os.path.join(processed_data_folder_name, drought_weather_shema_filename), index_col=0).squeeze("columns")

In [89]:
# Apply the schema to the loaded dataframe
df_reloaded = df_reloaded.astype(reloaded_schema.to_dict())

In [90]:
df_reloaded.equals(df_decrees_weather_communes_df)

True

In [91]:
df_reloaded.shape

(855388, 55)

In [92]:
df_reloaded

,insee_1,nom_commune_1,latitude_1,longitude_1,year_1,decision_1,Code Postal_1,Département_1,Région_1,Code Département_1,...,stl2_mean_2,slt_sum_2,slt_mean_2,swvl1_sum_2,swvl1_mean_2,swvl2_sum_2,swvl2_mean_2,latitude_rad_2,longitude_rad_2,distance_km
0,10002,AILLEVILLE,48.255000,4.694493,2000,0,10200,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.360728,36.0,3.0,4.290780,0.357565,4.225537,0.352128,0.842121,0.082903,4.147094
1,10003,AIX-EN-OTHE,48.197575,3.736328,2000,0,10160,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.673390,24.0,2.0,4.221337,0.351778,4.156231,0.346353,0.842121,0.065450,5.916774
2,10004,ALLIBAUDIERES,48.586400,4.122928,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.781789,24.0,2.0,4.192894,0.349408,4.119763,0.343314,0.846485,0.069813,13.198245
3,10005,AMANCE,48.291854,4.487049,2000,0,10140,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.527883,24.0,2.0,4.238762,0.353230,4.164776,0.347065,0.842121,0.078540,4.751647
4,10006,ARCIS-SUR-AUBE,48.527827,4.141971,2000,0,10700,['AUBE'],['CHAMPAGNE-ARDENNE'],10,...,11.784230,24.0,2.0,4.209328,0.350777,4.135861,0.344655,0.846485,0.074176,8.537810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35607,95675,VILLERON,49.060843,2.534511,2023,0,95380,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.806976,24.0,2.0,3.870941,0.322578,3.820614,0.318384,0.855211,0.043633,7.218142
35608,95676,VILLERS-EN-ARTHIES,49.085900,1.730396,2023,0,95510,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.669118,24.0,2.0,3.961685,0.330140,3.880611,0.323384,0.855211,0.030543,9.657919
35609,95678,VILLIERS-ADAM,49.070289,2.239509,2023,0,95840,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.757823,24.0,2.0,3.926819,0.327235,3.863033,0.321919,0.855211,0.039270,7.853091
35610,95682,VILLIERS-LE-SEC,49.074309,2.386890,2023,0,95720,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.806976,24.0,2.0,3.870941,0.322578,3.820614,0.318384,0.855211,0.043633,11.672969
35611,95690,WY-DIT-JOLI-VILLAGE,49.095820,1.825029,2023,0,95420,"[""VAL-D'OISE""]",['ILE-DE-FRANCE'],95,...,12.669118,24.0,2.0,3.961685,0.330140,3.880611,0.323384,0.855211,0.030543,11.975907

In [93]:
df_reloaded.dtypes

insee_1                object
nom_commune_1          object
latitude_1            float64
longitude_1           float64
year_1                  int64
decision_1              int64
Code Postal_1          object
Département_1          object
Région_1               object
Code Département_1     object
Code Région_1           int64
latitude_rad_1        float64
longitude_rad_1       float64
latitude_2            float64
longitude_2           float64
year_2                  int32
t2m_z_sum_2           float64
t2m_z_mean_2          float64
tp_z_sum_2            float64
tp_z_mean_2           float64
e_z_sum_2             float64
e_z_mean_2            float64
pev_z_sum_2           float64
pev_z_mean_2          float64
stl1_z_sum_2          float64
stl1_z_mean_2         float64
stl2_z_sum_2          float64
stl2_z_mean_2         float64
slt_z_sum_2           float64
slt_z_mean_2          float64
swvl1_z_sum_2         float64
swvl1_z_mean_2        float64
swvl2_z_sum_2         float64
swvl2_z_mean_2        float64
t2m_sum_2             float32
t2m_mean_2            float32
tp_sum_2              float32
tp_mean_2             float32
e_sum_2               float32
e_mean_2              float32
pev_sum_2             float32
pev_mean_2            float32
stl1_sum_2            float32
stl1_mean_2           float32
stl2_sum_2            float32
stl2_mean_2           float32
slt_sum_2             float32
slt_mean_2            float32
swvl1_sum_2           float32
swvl1_mean_2          float32
swvl2_sum_2           float32
swvl2_mean_2          float32
latitude_rad_2        float64
longitude_rad_2       float64
distance_km           float64
dtype: object